FROM node:20-alpine as build

WORKDIR /app

COPY pfe-project-front/package*.json ./

RUN npm install --legacy-peer-deps

COPY pfe-project-front/ .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy static assets from builder
COPY --from=build /app/build /usr/share/nginx/html/

# Expose the port we need
EXPOSE 8097

CMD ["nginx", "-g", "daemon off;"]
