FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=projetpfeagil

COPY projetpfeagil.sql /docker-entrypoint-initdb.d/

# Ajout de la configuration d'authentification
RUN echo "default_authentication_plugin=mysql_native_password" >> /etc/mysql/my.cnf

VOLUME /var/lib/mysql
