version: '3.8'

services:
  frontend:
    build:
      context: ./pfe-project-front
      dockerfile: Dockerfile
    ports:
      - "8095:80"
    volumes:
      - ./pfe-project-front/public:/usr/share/nginx/html/public
      - uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=ProjetPfeAgil
      - NODE_ENV=production
      - EMAIL_USER=nidhal.boughanmi@esprit.tn
      - EMAIL_PASS=Nidhalboughanmi123
      - HUGGINGFACE_API_KEY=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
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ProjetPfeAgil
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  db-data: