USE ProjetPfeAgil;

ALTER TABLE RECLAMATION 
ADD COLUMN IF NOT EXISTS priority ENUM('URGENT', 'MOYEN', 'NORMAL') DEFAULT 'NORMAL',
ADD COLUMN IF NOT EXISTS satisfaction ENUM('TRES_SATISFAIT', 'SATISFAIT', 'NEUTRE', 'PEU_SATISFAIT', 'INSATISFAIT') DEFAULT 'NEUTRE',
ADD COLUMN IF NOT EXISTS gravite ENUM('HAUTE', 'MOYENNE', 'FAIBLE') DEFAULT 'FAIBLE',
ADD COLUMN IF NOT EXISTS sentiment_score FLOAT,
ADD COLUMN IF NOT EXISTS estimatedResolutionTime INT,
ADD COLUMN IF NOT EXISTS actualResolutionTime INT,
ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
