FROM node:20-alpine as build

WORKDIR /app

# Installer d'abord les dépendances
COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

# Copier le reste des fichiers
COPY . .

# Build l'application
RUN npm run build

# Étape de production avec Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Nettoyage
RUN rm -rf /usr/share/nginx/html/node_modules

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
